#!/usr/local/bin/pwsh

git clone git@github.com:iquipsys-positron/iqs-devenv
git clone git@github.com:iquipsys-positron/iqs-libs-protocols-node
git clone git@github.com:iquipsys-positron/iqs-clients-statistics-node
git clone git@github.com:iquipsys-positron/iqs-facades-public-node

git clone git@github.com:iquipsys-positron/iqs-services-devices-node
git clone git@github.com:iquipsys-positron/iqs-services-controlobjects-node
git clone git@github.com:iquipsys-positron/iqs-services-objectgroups-node
git clone git@github.com:iquipsys-positron/iqs-services-dataprofiles-node
git clone git@github.com:iquipsys-positron/iqs-services-deviceprofiles-node
git clone git@github.com:iquipsys-positron/iqs-services-zones-node
git clone git@github.com:iquipsys-positron/iqs-services-eventrules-node
git clone git@github.com:iquipsys-positron/iqs-services-resolutions-node
git clone git@github.com:iquipsys-positron/iqs-services-deviceconfigs-node
git clone git@github.com:iquipsys-positron/iqs-services-shifts-node
git clone git@github.com:iquipsys-positron/iqs-services-emergencyplans-node
git clone git@github.com:iquipsys-positron/iqs-services-locations-node
git clone git@github.com:iquipsys-positron/iqs-services-gateways-node
git clone git@github.com:iquipsys-positron/iqs-services-eventtemplates-node
git clone git@github.com:iquipsys-positron/iqs-services-agreements-node
git clone git@github.com:iquipsys-positron/iqs-services-rosters-node
git clone git@github.com:iquipsys-positron/iqs-services-attendance-node
git clone git@github.com:iquipsys-positron/iqs-services-objectstates-node
git clone git@github.com:iquipsys-positron/iqs-services-currobjectstates-node
git clone git@github.com:iquipsys-positron/iqs-services-currdevicestates-node
git clone git@github.com:iquipsys-positron/iqs-services-opevents-node
git clone git@github.com:iquipsys-positron/iqs-services-incidents-node
git clone git@github.com:iquipsys-positron/iqs-services-signals-node
git clone git@github.com:iquipsys-positron/iqs-services-corrections-node
git clone git@github.com:iquipsys-positron/iqs-services-eventgeneration-node
git clone git@github.com:iquipsys-positron/iqs-services-stateupdates-node
git clone git@github.com:iquipsys-positron/iqs-services-eventgeneration-node
git clone git@github.com:iquipsys-positron/iqs-services-mqttgateway-node
git clone git@github.com:iquipsys-positron/iqs-services-restgateway-node
git clone git@github.com:iquipsys-positron/iqs-services-teltonikagateway-node

git clone git@github.com:iquipsys-positron/iqs-clients-devices-node
git clone git@github.com:iquipsys-positron/iqs-clients-controlobjects-node
git clone git@github.com:iquipsys-positron/iqs-clients-objectgroups-node
git clone git@github.com:iquipsys-positron/iqs-clients-dataprofiles-node
git clone git@github.com:iquipsys-positron/iqs-clients-deviceprofiles-node
git clone git@github.com:iquipsys-positron/iqs-clients-zones-node
git clone git@github.com:iquipsys-positron/iqs-clients-eventrules-node
git clone git@github.com:iquipsys-positron/iqs-clients-resolutions-node
git clone git@github.com:iquipsys-positron/iqs-clients-deviceconfigs-node
git clone git@github.com:iquipsys-positron/iqs-clients-shifts-node
git clone git@github.com:iquipsys-positron/iqs-clients-emergencyplans-node
git clone git@github.com:iquipsys-positron/iqs-clients-locations-node
git clone git@github.com:iquipsys-positron/iqs-clients-gateways-node
git clone git@github.com:iquipsys-positron/iqs-clients-eventtemplates-node
git clone git@github.com:iquipsys-positron/iqs-clients-agreements-node
git clone git@github.com:iquipsys-positron/iqs-clients-rosters-node
git clone git@github.com:iquipsys-positron/iqs-clients-attendance-node
git clone git@github.com:iquipsys-positron/iqs-clients-objectstates-node
git clone git@github.com:iquipsys-positron/iqs-clients-currobjectstates-node
git clone git@github.com:iquipsys-positron/iqs-clients-currdevicestates-node
git clone git@github.com:iquipsys-positron/iqs-clients-opevents-node
git clone git@github.com:iquipsys-positron/iqs-clients-incidents-node
git clone git@github.com:iquipsys-positron/iqs-clients-signals-node
git clone git@github.com:iquipsys-positron/iqs-clients-corrections-node
git clone git@github.com:iquipsys-positron/iqs-clients-stateupdates-node
git clone git@github.com:iquipsys-positron/iqs-clients-eventgeneration-node
git clone git@github.com:iquipsys-positron/iqs-clients-mqttgateway-node
git clone git@github.com:iquipsys-positron/iqs-clients-restgateway-node
